food:
  cheez-it:
  suger_box:
  tomato_can:
  mustard:
  tuna_can:
  choco_box:
  strawberry_box:
  spam:
  banana:
  strawberry:
  apple:
  lemon:
  peach:
  pear:
  orange:
  plum:

shape:
  soccer_ball:
  soft_ball:
  base_ball:
  tennis_ball:
  racquet_ball:
  golf_ball:
  chain:
  foam_brick:
  dice:
  marbies:
  cup:

kitchen:
  pitcher_base:
  cleanser_bottle:
  spray_bottle:
  bowl:
  mug:
  sponge:
  plate:
  plate:
  fork:
  spatula:

task:
  padlock:
  clamp:
  wood_block:
  9-peg:
  lego:
  rubiks:

orientation:
  spoon:
  marker:
